// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10h1_YSHxGUnW8CxgeGU-M6IKim-c7-Y',
    appId: '1:905285419964:android:59eaf2b1f20160d03721b9',
    messagingSenderId: '905285419964',
    projectId: 'contact-app-f1ae3',
    storageBucket: 'contact-app-f1ae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfMpE9lmGElYYXH5zb8DBvXYaq5oDl_o',
    appId: '1:905285419964:ios:6766675e57ff12db3721b9',
    messagingSenderId: '905285419964',
    projectId: 'contact-app-f1ae3',
    storageBucket: 'contact-app-f1ae3.firebasestorage.app',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzfMpE9lmGElYYXH5zb8DBvXYaq5oDl_o',
    appId: '1:905285419964:ios:6766675e57ff12db3721b9',
    messagingSenderId: '905285419964',
    projectId: 'contact-app-f1ae3',
    storageBucket: 'contact-app-f1ae3.firebasestorage.app',
    iosBundleId: 'com.example.contact',
  );
}
